import { Scene } from './scene.js'
import { Rect } from './objects/rect.js'
import { Position } from './base-types/position.js'
import { PlayerKeyboardStatus } from './keyboard/player-keyboard-status.js'
import { canvas } from './global/canvas.js'
import { Area } from './base-types/area.js'
import { RewardManager } from './managers/reward-manager.js'
import { AiRectManager } from './managers/ai-rect-manager.js'
import { Size } from './base-types/size.js'
import { Direction } from './base-types/direction.js'
import { Speed } from './base-types/speed.js'
import { ScorePanel } from './panels/score-panel.js'
import { GameData } from './game-data.js'
import { Settings } from './settings.js'
import { PlayerPanel } from './panels/player-panel.js'
import { ImageManager } from './managers/image-manager.js'
import { SceneStatus } from './base-types/scene-status.js'
import { SceneManager } from './managers/scene-manager.js'

const sceneManager = new SceneManager()
sceneManager.createScene()